## Basic Stats and Linear Algebra

In [1]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([6, 4, 2])

### Basic arithmetic operations

In [2]:
x + y

array([7, 6, 5])

In [3]:
x - y

array([-5, -2,  1])

In [4]:
x * y

array([6, 8, 6])

In [5]:
x / y

array([ 0.16666667,  0.5       ,  1.5       ])

In [6]:
x * 2

array([2, 4, 6])

In [7]:
y + 1

array([7, 5, 3])

In [8]:
x / 0

c:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ inf,  inf,  inf])

In [9]:
x.sum()

6

In [10]:
w = np.array([[1, 2], [3, 4]])
z = np.array([[5, 6], [7, 8]])

z

array([[5, 6],
       [7, 8]])

In [11]:
z.sum()

26

In [12]:
w + z

array([[ 6,  8],
       [10, 12]])

In [13]:
w * 2

array([[2, 4],
       [6, 8]])

### Basic stats

In [14]:
x

array([1, 2, 3])

In [15]:
x.min()

1

In [16]:
x.max()

3

In [17]:
x.mean()

2.0

#### Variance

$\mu$ is the mean

$Var(X) = \frac{1}{n}\sum_{i=1}^{n} (x_{i} - \mu)^2$ 

In [18]:
x.var()

0.66666666666666663

#### Standard deviation

$\sigma = \sqrt{Var(X)}$

In [19]:
x.std()

0.81649658092772603

In [20]:
x

array([1, 2, 3])

In [21]:
x.argmin()

0

In [22]:
x[x.argmin()] == x.min()

True

In [23]:
x.argmax()

2

### Matrices and linear algebra

In [24]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
A.shape

(2, 3)

In [26]:
A.mean()

3.5

In [27]:
A.max()

6

In [28]:
A.argmax()

5

#### Transpose

Switch rows and columns

In [29]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
B.shape

(3, 2)

In [32]:
C = np.random.randint(0, 10, (2, 3))
C

array([[5, 7, 8],
       [5, 8, 2]])

In [33]:
C.shape

(2, 3)

In [34]:
A + B

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [35]:
A + C

array([[ 6,  9, 11],
       [ 9, 13,  8]])

#### Dot-product

The dot-product requires the matrices to be aligned 

e.g. A.shape = 2x3, B.shape = 3x2, output 2x2

In [36]:
np.dot(A, B)

array([[14, 32],
       [32, 77]])

In [37]:
np.dot(A, C)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)